name: emoup
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_login: ^1.1.0
  shared_preferences: ^2.0.5
  flutter_spinkit: ^4.1.2
  google_fonts: ^2.0.0
  file_picker: ^3.0.1
  intl: ^0.17.0
  flutter_image_compress: ^1.0.0-nullsafety
  qrscan: ^0.3.1
  url_launcher: ^6.0.3
  path_provider: ^2.0.1
  maps_launcher: ^2.0.0
  chips_choice: ^2.0.1
  stacked_card_carousel: ^0.0.2+1
  syncfusion_flutter_charts: ^19.1.55+1
  firebase_storage: ^8.0.3
  cloud_firestore: ^1.0.4
  firebase_core: ^1.0.3
  encrypt: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
